export const appActionTypes = {
	CHANGE_SEARCH_TERM: 'CHANGE_SEARCH_TERM',
	GIFS_FETCH_SUCCEEDED: 'GIFS_FETCH_SUCCEEDED',
	GIFS_FETCH_FAILED: 'GIFS_FETCH_FAILED',
	GIFS_FETCH_REQUESTED: 'GIFS_FETCH_REQUESTED',
};
